### ISSUE TITLE
Better builders screen

### ISSUE THREAD

**Issue by mikepurvis** [mikeferguson/buildbot-ros#27]
Once you're building more than a few packages, the builders screen gets to be a mess. It doesn't need to be as fancy as the buildfarm one, but the ideal from my perspective would be a grid with the packages down the side, and hdoc/htest/ph64/ph32 etc along the top.

I'll probably work on this at some point and would be happy to contribute it back.

**Comment by mikeferguson** [comment]
No longer supported, about to archive
