### ISSUE TITLE
Aptly to replace reprepro?

### ISSUE THREAD

**Issue by mikepurvis** [mikeferguson/buildbot-ros#45]
This is the killer feature, once it lands: https://github.com/smira/aptly/issues/116

It exposes a REST API to upload packages, which removes all the fuss of having to manually manage concurrency around the apt repo.

**Comment by rohbotics** [comment]
Looks like it made it in 0.9 smira/aptly#116

**Comment by mikeferguson** [comment]
No longer supported, about to archive
