### ISSUE TITLE
Add email alerts, installation notes

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/buildbot-ros#5]
The code for setting this up is pretty much trivial, but we need to install an SMTP server for it to work, and that should be documented.

**Comment by asmodehn** [comment]
Agreed.
I would be interested at setting up email notifications for people who committed latest change if the _testbuild_ fails... and if a SMTP server is configured in buildbot-ros.
Also probably worth configuring some success email if a binarydeb was successful.

I am wondering where to put the SMTP configuration though ( like the OAuth and login information, it should probably be in a file that is not committed to buildbot-ros repository ).
Any idea ?

**Comment by mikeferguson** [comment]
No longer supported, about to archive
