### ISSUE TITLE
First docbuild fails with base-trusty-amd64.cow does not exist

### ISSUE THREAD

**Issue by asmodehn** [mikeferguson/buildbot-ros#57]
I recently managed to setup a local buildbot master and slave with a custom distribution.yaml ( trying to build https://github.com/stonier/ecl_core as a first step ) .
I could also properly configure the build job ( I think... ).

When I run that build job, I come across these error ( not sure if they are related ) that are probably related to something wrong i did with the setup : 

docbuild : 
```
cannot canonicalize filename /var/cache/pbuilder/base-trusty-amd64.cow, does not exist
```

debbuild : 
```
Upon execvpe cowbuilder-update.py ['cowbuilder-update.py', 'trusty', 'amd64', 'http://packages.ros.org/ros.key'] in environment id 140562951466632
:Traceback (most recent call last):
  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/process.py", line 424, in _fork
    environment)
  File "/home/buildbot/.virtualenvs/buildbot-env/local/lib/python2.7/site-packages/twisted/internet/process.py", line 502, in _execChild
    os.execvpe(executable, args, environment)
  File "/home/buildbot/.virtualenvs/buildbot-env/lib/python2.7/os.py", line 353, in execvpe
    _execvpe(file, args, env)
  File "/home/buildbot/.virtualenvs/buildbot-env/lib/python2.7/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
program finished with exit code 1
elapsedTime=0.001896
```

Any hint ?
Any additional info I could provide to help finding out the cause ?

**Comment by asmodehn** [comment]
Hmm I guess, since I've never used cowbuilder before, that some setup step is missing form the documentation ?

Should I spend some time trying to get it to work, or is it better that I switch to docker right away since I can see documentation about it ?

**Comment by mikeferguson** [comment]
The first message appears to actually be a previously unreported bug/limitation: the docbuild does not update the cowbuilder. This should go away once the cowbuilder is created, which leads to the second error trace...

It seems that "cowbuilder-update.py" is not on your path? I imagine this is an environment setup issue? See especially the line in buildslave setup about updating the path: 

```
echo "export PATH=/home/buildbot/buildbot-ros/scripts:${PATH}" >> buildbot-env/bin/activate
```

(obviously, this might need to be updated depending on where you installed)

**Comment by asmodehn** [comment]
Indeed, I forgot to deactivate/reactivate my virtual environment after making that change :)
I ll move on to the next step now. Thanks a lot !
