### ISSUE TITLE
Testbuild builds two times the same commit

### ISSUE THREAD

**Issue by asmodehn** [mikeferguson/buildbot-ros#62]
If two commits are made very close to each other in the development branch, buildbot will build two times the latest commit.

**Comment by mikeferguson** [comment]
This is a shortcoming of the GitPoller -- as I understand it, there are other pollers that could be used, but they would insert a delay before starting to build.

Not something I plan to work on, Pull Requests welcome.

**Comment by mikeferguson** [comment]
No longer supported, about to archive
