### ISSUE TITLE
Support REP143

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/buildbot-ros#63]
Introduces several changes, notably removing the build files. @dirk-thomas has an initial (not yet tested) pass here: https://github.com/mikeferguson/buildbot-ros/compare/master...dirk-thomas:rep143?expand=1 that I will be looking at this weekend.

Need to also tag an 0.2.0 release before moving to REP-143 and build config repo, and probably will tag an 0.3.0 when the 143 support is in

**Comment by pbeeson** [comment]
Is this project still being developed?

**Comment by mikeferguson** [comment]
Definitely still in use at several places. I would classify more as "lightly maintained" -- there isn't a lot of active development going on in the mainline.

**Comment by mikeferguson** [comment]
No longer supported, about to archive
