### ISSUE TITLE
Xenial support

### ISSUE THREAD

**Issue by rohbotics** [mikeferguson/buildbot-ros#66]
I am trying to get builds for Kinetic/Xenial from buildbot-ros.

Looks like git-buildpackage is very different from Trusty to Xenial. (0.6.9 => 0.7.2)

Making migration complicated is the fact that `git-buildpackage --version` doesn't work in xenial, because that is no longer a program, as it is completely replaced by gpb. `gpb --version` doesn't work in trusty, as there is no version option in trusty. 

Any thoughts on how I should get around that issue?

**Comment by mikeferguson** [comment]
Probably resolved by https://github.com/mikeferguson/buildbot-ros/pull/71 (once reviewed and merged)

**Comment by mikeferguson** [comment]
No longer supported, about to archive
