### ISSUE TITLE
Debian Jessie -> unmet dependencies

### ISSUE THREAD

**Issue by SquirrelCZE** [mikeferguson/buildbot-ros#67]
Hi folks!

I am trying to build mine packages for debian jessie, and got this error:
```

dpkg-checkbuilddeps: Unmet build dependencies: ros-kinetic-catkin
W: Unmet build-dependency in source
dpkg-buildpackage: error: unable to determine source changed b
```

anybody any tips how to approach it? I am really confused because it's first proper experience with buildbot and I don't know where/what to search for

**Comment by mikeferguson** [comment]
Within your build farm configuration, either your sources are not correct, or possibly the keys are not correct.
