### ISSUE TITLE
python3 and updating buildbot

### ISSUE THREAD

**Issue by tylerjw** [mikeferguson/buildbot-ros#75]
I'm not sure what is involved here or even what would be gained (other than being able to run this on newer versions of utunbut without python2 easiesr).  It looks like buildbot is dropping support for python2.

**Comment by mikeferguson** [comment]
I'm also not sure what is involved in updating - I know a number of projects took the 2->3 transition as opportunity to really overhaul their APIs, not sure what the case is for buildbot itself.

PRs are welcome - as you can see from the commit history, I haven't been very active on this project in quite a while (I've done a better job these days of not being DevOps in my day job, and also been able to leverage industrial-ci for what little DevOps I do).

**Comment by mikeferguson** [comment]
No longer supported, about to archive
